function J = JSwingFN(in1)
%JSWINGFN
%    J = JSWINGFN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Feb-2019 15:14:22

alphaL = in1(4,:);
alphaR = in1(2,:);
betaL = in1(5,:);
betaR = in1(3,:);
phi = in1(1,:);
t2 = alphaR+phi;
t3 = cos(t2);
t4 = alphaR+betaR+phi;
t5 = cos(t4);
t6 = alphaL+phi;
t7 = cos(t6);
t8 = t7.*(2.0./5.0);
t9 = alphaL+betaL+phi;
t10 = cos(t9);
t11 = t10.*(2.0./5.0);
t12 = sin(t4);
t13 = sin(t2);
t14 = sin(t9);
t15 = t14.*(2.0./5.0);
t16 = sin(t6);
t17 = t16.*(2.0./5.0);
J = reshape([t3.*(-2.0./5.0)-t5.*(2.0./5.0)+t8+t11,t12.*(-2.0./5.0)-t13.*(2.0./5.0)+t15+t17,t3.*(-2.0./5.0)-t5.*(2.0./5.0),t12.*(-2.0./5.0)-t13.*(2.0./5.0),t5.*(-2.0./5.0),t12.*(-2.0./5.0),t8+t11,t15+t17,t11,t15],[2,5]);
