function out1 = JYSwingFN(in1)
%JYSWINGFN
%    OUT1 = JYSWINGFN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Feb-2019 15:14:22

alphaL = in1(4,:);
alphaR = in1(2,:);
betaL = in1(5,:);
betaR = in1(3,:);
phi = in1(1,:);
t2 = alphaR+betaR+phi;
t3 = sin(t2);
t4 = alphaR+phi;
t5 = sin(t4);
t6 = alphaL+betaL+phi;
t7 = sin(t6);
t8 = t7.*(2.0./5.0);
t9 = alphaL+phi;
t10 = sin(t9);
t11 = t10.*(2.0./5.0);
out1 = [t3.*(-2.0./5.0)-t5.*(2.0./5.0)+t8+t11,t3.*(-2.0./5.0)-t5.*(2.0./5.0),t3.*(-2.0./5.0),t8+t11,t8];
