function linkPos = LinkPosFN(in1)
%LINKPOSFN
%    LINKPOS = LINKPOSFN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Feb-2019 15:15:04

alphaL = in1(4,:);
alphaR = in1(2,:);
betaL = in1(5,:);
betaR = in1(3,:);
phi = in1(1,:);
t2 = alphaR+betaR+phi;
t3 = sin(t2);
t4 = alphaR+phi;
t5 = cos(t2);
t6 = t5.*(2.0./5.0);
t7 = sin(t4);
t8 = cos(t4);
t9 = t8.*(2.0./5.0);
t12 = t3.*(2.0./5.0);
t13 = t7.*(2.0./5.0);
t10 = -t12-t13;
t11 = t6+t9;
t14 = alphaL+phi;
t15 = sin(t14);
t16 = t15.*(2.0./5.0);
t17 = cos(t14);
t18 = alphaL+betaL+phi;
linkPos = reshape([0.0,t3.*(-2.0./5.0),t10,t3.*(-2.0./5.0)-t7.*(2.0./5.0)-sin(phi).*(1.2e1./2.5e1),t10,-t12-t13+t16,-t12-t13+t16+sin(t18).*(2.0./5.0),0.0,t6,t11,t6+t9+cos(phi).*(1.2e1./2.5e1),t11,t6+t9-t17.*(2.0./5.0),t6+t9-t17.*(2.0./5.0)-cos(t18).*(2.0./5.0)],[7,2]);
