function M = MassMatrixFN(in1)
%MASSMATRIXFN
%    M = MASSMATRIXFN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Feb-2019 15:14:21

alphaL = in1(4,:);
alphaR = in1(2,:);
betaL = in1(5,:);
betaR = in1(3,:);
t2 = alphaL-alphaR+betaL-betaR;
t3 = cos(t2);
t4 = alphaL-alphaR+betaL;
t5 = cos(t4);
t6 = -alphaL+alphaR+betaR;
t7 = cos(t6);
t8 = alphaR+betaR;
t9 = cos(t8);
t10 = cos(alphaR);
t11 = cos(betaR);
t12 = t11.*8.6176;
t13 = alphaL-alphaR;
t14 = cos(t13);
t15 = t9.*(1.44e2./1.25e2);
t16 = cos(betaL);
t17 = t16.*(3.84e2./6.25e2);
t18 = t10.*(1.44e2./1.25e2);
t21 = t3.*(1.92e2./6.25e2);
t22 = t5.*(1.92e2./6.25e2);
t23 = t7.*(5.07e2./6.25e2);
t24 = t14.*(5.07e2./6.25e2);
t19 = t12+t15+t18-t21-t22-t23-t24+9.4518;
t20 = t11.*4.3088;
t25 = t20+4.88992;
t26 = -t21-t22-t23-t24;
t27 = -t21-t23;
t28 = t16.*(1.92e2./6.25e2);
t29 = -t21-t22;
t30 = t28+3.8432e-1;
M = reshape([t3.*(-3.84e2./6.25e2)-t5.*(3.84e2./6.25e2)-t7.*1.6224+t9.*(2.88e2./1.25e2)+t10.*(2.88e2./1.25e2)+t12-t14.*1.6224+t17+1.29216e1,t19,t15+t20-t21-t23+4.88992,t17-t21-t22-t23-t24+1.4486,-t21-t22+t28+3.8432e-1,t19,t12+9.4518,t25,t26,t29,t3.*(-1.92e2./6.25e2)-t7.*(5.07e2./6.25e2)+t15+t20+4.88992,t25,4.88992,t27,-t21,t3.*(-1.92e2./6.25e2)-t5.*(1.92e2./6.25e2)-t7.*(5.07e2./6.25e2)-t14.*(5.07e2./6.25e2)+t17+1.4486,t26,t27,t17+1.4486,t30,t3.*(-1.92e2./6.25e2)-t5.*(1.92e2./6.25e2)+t28+3.8432e-1,t29,-t21,t30,3.8432e-1],[5,5]);
